"""
Intent catalog: the two data structures that drive the new router.

INTENT_LOOKUP   — deterministic (intent, frozenset(entity_types)) → query_id
INTENT_SLOTS    — for each intent, which entity types to try to extract
INTENT_LIST     — all valid intent names (used to constrain LLM output)
"""

# ── Step 3 lookup table — zero collisions, covers all 71 query IDs ────────────

INTENT_LOOKUP: dict[tuple[str, frozenset], str] = {
    # Enrollment
    ("enrollment_count",               frozenset()                         ): "D01",
    ("enrollment_count",               frozenset(["district"])             ): "T01",
    ("enrollment_count",               frozenset(["block"])                ): "T48",
    ("enrollment_count",               frozenset(["block", "district"])    ): "T11",
    ("enrollment_summary_by_district", frozenset()                         ): "D02",
    ("enrollment_summary_by_division", frozenset()                         ): "D03",
    ("enrollment_gender_breakdown",    frozenset()                         ): "D04",
    ("enrollment_gender_breakdown",    frozenset(["district"])             ): "T09",
    ("enrollment_gender_breakdown",    frozenset(["block"])                ): "T49",
    ("enrollment_age_distribution",    frozenset()                         ): "D05",
    ("enrollment_age_distribution",    frozenset(["district"])             ): "T36",
    ("enrollment_age_distribution",    frozenset(["block"])                ): "T50",
    ("enrollment_source_breakdown",    frozenset()                         ): "D06",
    ("enrollment_source_breakdown",    frozenset(["district"])             ): "T37",
    ("enrollment_source_breakdown",    frozenset(["block"])                ): "T51",
    ("enrollment_bis_status",          frozenset()                         ): "D07",
    ("enrollment_bis_status",          frozenset(["district"])             ): "T38",
    ("enrollment_bis_status",          frozenset(["block"])                ): "T52",
    ("enrollment_mobile_coverage",     frozenset()                         ): "D08",
    ("enrollment_mobile_coverage",     frozenset(["district"])             ): "T39",
    ("enrollment_mobile_coverage",     frozenset(["block"])                ): "T53",
    # Hospital
    ("hospital_count",                 frozenset()                         ): "D09",
    ("hospital_count",                 frozenset(["district"])             ): "T06",
    ("hospital_count",                 frozenset(["block"])                ): "T13",
    ("hospital_count_by_district",     frozenset()                         ): "D10",
    ("hospital_density",               frozenset()                         ): "D11",
    ("specialty_coverage",             frozenset()                         ): "D12",
    ("specialty_coverage",             frozenset(["district"])             ): "T40",
    ("specialty_coverage",             frozenset(["block"])                ): "T54",
    ("hospital_license_status",        frozenset()                         ): "D13",
    ("hospital_license_status",        frozenset(["district"])             ): "T41",
    ("hospital_license_status",        frozenset(["block"])                ): "T55",
    ("hospital_license_status",        frozenset(["hospital"])             ): "T18",
    ("hospital_bed_capacity",          frozenset()                         ): "D14",
    ("hospital_bed_capacity",          frozenset(["district"])             ): "T42",
    ("hospital_bed_capacity",          frozenset(["block"])                ): "T56",
    ("hospital_staff_ratio",           frozenset()                         ): "D15",
    ("hospital_staff_ratio",           frozenset(["district"])             ): "T43",
    ("hospital_staff_ratio",           frozenset(["block"])                ): "T57",
    ("hospital_performance",           frozenset(["hospital"])             ): "T15",
    ("hospital_specialties",           frozenset(["hospital"])             ): "T16",
    ("hospital_type_utilization",      frozenset()                         ): "D25",
    ("hospital_type_utilization",      frozenset(["district"])             ): "T29",
    ("hospital_type_utilization",      frozenset(["block"])                ): "T63",
    # Claims
    ("claims_total",                   frozenset()                         ): "D16",
    ("claims_total",                   frozenset(["month", "year"])        ): "T32",
    ("case_volume_trend",              frozenset()                         ): "D17",
    ("case_volume_trend",              frozenset(["district"])             ): "T05",
    ("case_volume_trend",              frozenset(["block"])                ): "T58",
    ("case_volume_trend",              frozenset(["hospital"])             ): "T17",
    ("claims_summary_by_district",     frozenset()                         ): "D18",
    ("claims_summary_by_division",     frozenset()                         ): "D19",
    ("claims_summary",                 frozenset()                         ): "D18",
    ("claims_summary",                 frozenset(["district"])             ): "T02",
    ("claims_summary",                 frozenset(["block"])                ): "T59",
    ("claims_summary",                 frozenset(["block", "district"])    ): "T12",
    ("claim_status_distribution",      frozenset()                         ): "D20",
    ("claim_status_distribution",      frozenset(["district"])             ): "T27",
    ("claim_status_distribution",      frozenset(["block"])                ): "T60",
    ("claims_by_status",               frozenset()                           ): "D20",
    ("claims_by_status",               frozenset(["claim_status"])           ): "D20",
    ("claims_by_status",               frozenset(["claim_status","district"])): "T28",
    ("claim_approval_rate",            frozenset(["hospital"])             ): "T19",
    ("case_volume_by_district",        frozenset()                         ): "D18",
    ("case_volume_by_district",        frozenset(["year"])                 ): "T33",
    ("block_case_volume",              frozenset()                         ): "D18",
    ("block_case_volume",              frozenset(["district"])             ): "T10",
    ("annual_totals",                  frozenset()                         ): "D18",
    ("annual_totals",                  frozenset(["year"])                 ): "T33",
    ("annual_totals",                  frozenset(["year", "district"])     ): "T31",
    ("district_comparison",            frozenset(["district","district_2"])): "T26",
    # Specialty & Diagnosis
    ("specialty_utilization",          frozenset()                         ): "D21",
    ("specialty_utilization",          frozenset(["specialty"])            ): "T21",
    ("specialty_utilization",          frozenset(["specialty", "district"])): "T25",
    ("specialty_by_district",          frozenset(["specialty"])            ): "T22",
    ("top_hospitals_by_specialty",     frozenset(["specialty"])            ): "T24",
    ("top_procedures",                 frozenset()                         ): "D22",
    ("top_procedures",                 frozenset(["district"])             ): "T44",
    ("top_procedures",                 frozenset(["block"])                ): "T65",
    ("top_diagnoses",                  frozenset()                         ): "D23",
    ("top_diagnoses",                  frozenset(["district"])             ): "T45",
    ("top_diagnoses",                  frozenset(["block"])                ): "T66",
    ("top_diagnoses",                  frozenset(["hospital"])             ): "T20",
    ("top_diagnoses",                  frozenset(["block", "district"])    ): "T14",
    ("disease_category_breakdown",     frozenset()                         ): "D24",
    ("disease_category_breakdown",     frozenset(["district"])             ): "T04",
    ("disease_category_breakdown",     frozenset(["block"])                ): "T67",
    ("disease_category_trend",         frozenset(["diagnosis_category"])   ): "T23",
    ("seasonal_pattern",               frozenset()                         ): "D27",
    ("seasonal_pattern",               frozenset(["diagnosis_category"])   ): "T35",
    # Financial
    ("settlement_tat",                 frozenset()                         ): "D31",
    ("settlement_tat",                 frozenset(["district"])             ): "T07",
    ("settlement_tat",                 frozenset(["block"])                ): "T61",
    ("settlement_tat_portability",     frozenset()                         ): "D32",
    ("settlement_tat_by_district",     frozenset()                         ): "D33",
    ("rejection_rate",                 frozenset()                         ): "D34",
    ("rejection_rate",                 frozenset(["district"])             ): "T08",
    ("rejection_rate",                 frozenset(["block"])                ): "T62",
    ("rejection_rate",                 frozenset(["month", "year"])        ): "T34",
    ("rejection_rate_trend",           frozenset()                         ): "D34",
    ("financial_summary",              frozenset()                         ): "D35",
    ("top_hospitals_by_claims",        frozenset()                         ): "D36",
    ("top_hospitals_by_claims",        frozenset(["district"])             ): "T03",
    ("top_hospitals_by_claims",        frozenset(["block"])                ): "T64",
    # Portability
    ("portability_volume",             frozenset()                         ): "D28",
    ("portability_volume",             frozenset(["district"])             ): "T30",
    ("portability_financials",         frozenset()                         ): "D29",
    ("portability_trend",              frozenset()                         ): "D30",
    # Other
    ("discharge_distribution",         frozenset()                         ): "D26",
    ("discharge_distribution",         frozenset(["district"])             ): "T46",
    ("discharge_distribution",         frozenset(["block"])                ): "T68",
    # Financial
    ("financial_summary",              frozenset(["district"])             ): "T47",
    ("financial_summary",              frozenset(["block"])                ): "T69",
    ("financial_summary",              frozenset(["year"])                 ): "T163",

    # ── Enrollment extensions (division / year / 2-district) ─────────────────
    ("enrollment_count",               frozenset(["division"])             ): "T128",
    ("enrollment_count",               frozenset(["year"])                 ): "T162",
    ("enrollment_count",               frozenset(["district", "district_2"])): "T112",

    # ── Claims extensions (division / year / 2-district / 2-division) ────────
    ("claims_summary",                 frozenset(["division"])             ): "T129",
    ("claims_summary",                 frozenset(["division", "division_2"])): "T140",
    ("claims_summary",                 frozenset(["district", "district_2"])): "T118",
    ("case_volume_trend",              frozenset(["division"])             ): "T135",
    ("case_volume_trend",              frozenset(["year"])                 ): "T167",
    ("top_hospitals_by_claims",        frozenset(["division"])             ): "T136",
    ("top_procedures",                 frozenset(["division"])             ): "T137",
    ("top_procedures",                 frozenset(["year"])                 ): "T166",
    ("top_diagnoses",                  frozenset(["division"])             ): "T138",
    ("settlement_tat",                 frozenset(["specialty"])            ): "T158",
    ("settlement_tat",                 frozenset(["division"])             ): "T132",
    ("settlement_tat",                 frozenset(["month", "year"])        ): "T165",
    ("settlement_tat",                 frozenset(["district", "district_2"])): "T114",
    ("rejection_rate",                 frozenset(["division"])             ): "T134",
    ("rejection_rate",                 frozenset(["district", "district_2"])): "T124",
    ("claim_approval_rate",            frozenset(["district", "district_2"])): "T113",
    ("hospital_type_utilization",      frozenset(["division"])             ): "T133",
    ("specialty_utilization",          frozenset(["specialty", "block"])   ): "T159",
    ("disease_category_trend",         frozenset(["diagnosis_category", "district"])): "T160",
    ("disease_category_trend",         frozenset(["diagnosis_category", "division"])): "T161",
    ("portability_volume",             frozenset(["block"])                ): "T110",

    # ── Enrolment quality / funnel ────────────────────────────────────────────
    ("beneficiary_utilization_gap",    frozenset()                         ): "D37",
    ("beneficiary_utilization_gap",    frozenset(["district"])             ): "T70",
    ("beneficiary_utilization_gap",    frozenset(["block"])                ): "T100",
    ("enrolment_to_card_lag",          frozenset()                         ): "D38",
    ("enrolment_to_card_lag",          frozenset(["district"])             ): "T71",
    ("enrolment_rejection_rate",       frozenset()                         ): "D39",
    ("enrolment_rejection_rate",       frozenset(["district"])             ): "T74",
    ("enrolment_rejection_rate",       frozenset(["block"])                ): "T250",
    ("enrolment_rejection_rate",       frozenset(["district", "district_2"])): "T271",
    ("authentication_mode_breakdown",  frozenset()                         ): "D40",
    ("authentication_mode_breakdown",  frozenset(["district"])             ): "T75",
    ("profile_completeness",           frozenset()                         ): "D41",
    ("profile_completeness",           frozenset(["district"])             ): "T169",
    ("profile_completeness",           frozenset(["block"])                ): "T228",
    ("profile_completeness",           frozenset(["district", "district_2"])): "T256",
    ("duplicate_beneficiaries",        frozenset()                         ): "D42",
    ("duplicate_beneficiaries",        frozenset(["district"])             ): "T72",
    ("duplicate_beneficiaries",        frozenset(["block"])                ): "T102",
    ("duplicate_beneficiaries",        frozenset(["district", "district_2"])): "T270",
    ("card_status_distribution",       frozenset()                         ): "D43",
    ("card_status_distribution",       frozenset(["district"])             ): "T73",
    ("card_status_distribution",       frozenset(["block"])                ): "T101",
    ("card_status_distribution",       frozenset(["district", "district_2"])): "T255",
    ("enrolment_trend",                frozenset()                         ): "D44",
    ("beneficiary_hospital_ratio",     frozenset()                         ): "D45",
    ("beneficiary_hospital_ratio",     frozenset(["district"])             ): "T170",
    ("beneficiary_hospital_ratio",     frozenset(["block"])                ): "T229",
    ("beneficiary_hospital_ratio",     frozenset(["district", "district_2"])): "T257",
    ("card_issuance_speed",            frozenset()                         ): "D105",
    ("card_issuance_speed",            frozenset(["district"])             ): "T173",
    ("card_issuance_speed",            frozenset(["block"])                ): "T231",
    ("card_issuance_speed",            frozenset(["district", "district_2"])): "T260",
    ("early_admission_rate",           frozenset()                         ): "D106",
    ("early_admission_rate",           frozenset(["district"])             ): "T174",
    ("early_admission_rate",           frozenset(["block"])                ): "T232",
    ("early_admission_rate",           frozenset(["district", "district_2"])): "T261",
    ("enrolment_to_treatment_funnel",  frozenset()                         ): "D95",
    ("enrolment_to_treatment_funnel",  frozenset(["district"])             ): "T99",
    ("enrolment_to_treatment_funnel",  frozenset(["block"])                ): "T111",

    # ── Hospital compliance / quality ─────────────────────────────────────────
    ("unauthorized_specialty_billing", frozenset()                         ): "D46",
    ("unauthorized_specialty_billing", frozenset(["district"])             ): "T82",
    ("bed_overcrowding",               frozenset()                         ): "D47",
    ("bed_overcrowding",               frozenset(["district"])             ): "T83",
    ("accreditation_status",           frozenset()                         ): "D48",
    ("accreditation_status",           frozenset(["district"])             ): "T84",
    ("infrastructure_gaps",            frozenset()                         ): "D50",
    ("delisted_with_cases",            frozenset()                         ): "D51",
    ("delisted_with_cases",            frozenset(["district"])             ): "T190",
    ("average_length_of_stay",         frozenset()                         ): "D52",
    ("average_length_of_stay",         frozenset(["hospital"])             ): "T143",
    ("average_length_of_stay",         frozenset(["specialty"])            ): "T156",
    ("average_length_of_stay",         frozenset(["district"])             ): "T87",
    ("average_length_of_stay",         frozenset(["district", "district_2"])): "T282",
    ("clinician_workload",             frozenset()                         ): "D53",
    ("clinician_workload",             frozenset(["district"])             ): "T85",
    ("hospital_concentration",         frozenset()                         ): "D112",
    ("hospital_concentration",         frozenset(["district"])             ): "T177",
    ("blocks_without_hospitals",       frozenset()                         ): "D123",
    ("blocks_without_hospitals",       frozenset(["district"])             ): "T179",

    # ── Claims / financial analytics ─────────────────────────────────────────
    ("claim_haircut",                  frozenset()                         ): "D54",
    ("claim_haircut",                  frozenset(["district"])             ): "T78",
    ("claim_haircut",                  frozenset(["district", "district_2"])): "T273",
    ("claim_value_by_procedure",       frozenset()                         ): "D55",
    ("claim_value_by_procedure",       frozenset(["district"])             ): "T79",
    ("claim_value_by_procedure",       frozenset(["hospital"])             ): "T147",
    ("claim_value_by_procedure",       frozenset(["specialty"])            ): "T154",
    ("claim_value_by_procedure",       frozenset(["block"])                ): "T106",
    ("claim_value_by_procedure",       frozenset(["district", "district_2"])): "T122",
    ("pending_claims_aging",           frozenset()                         ): "D56",
    ("pending_claims_aging",           frozenset(["district"])             ): "T80",
    ("failed_payments",                frozenset()                         ): "D57",
    ("failed_payments",                frozenset(["district"])             ): "T96",
    ("failed_payments",                frozenset(["hospital"])             ): "T151",
    ("failed_payments",                frozenset(["district", "district_2"])): "T274",
    ("documents_per_claim",            frozenset()                         ): "D58",
    ("documents_per_claim",            frozenset(["district"])             ): "T192",
    ("documents_per_claim",            frozenset(["district", "district_2"])): "T276",
    ("adjudication_query_rate",        frozenset()                         ): "D59",
    ("rejection_reasons",              frozenset()                         ): "D60",
    ("expenditure_trend",              frozenset()                         ): "D61",
    ("per_beneficiary_spend",          frozenset()                         ): "D62",
    ("per_beneficiary_spend",          frozenset(["district"])             ): "T81",
    ("per_beneficiary_spend",          frozenset(["division"])             ): "T139",
    ("per_beneficiary_spend",          frozenset(["district", "district_2"])): "T115",
    ("preauth_analysis",               frozenset()                         ): "D64",
    ("preauth_analysis",               frozenset(["district"])             ): "T76",
    ("preauth_analysis",               frozenset(["hospital"])             ): "T149",
    ("preauth_analysis",               frozenset(["block"])                ): "T105",
    ("preauth_analysis",               frozenset(["month", "year"])        ): "T164",
    ("preauth_analysis",               frozenset(["district", "district_2"])): "T121",
    ("addon_procedures",               frozenset()                         ): "D68",
    ("addon_procedures",               frozenset(["hospital"])             ): "T142",
    ("claim_submission_lag",           frozenset()                         ): "D96",
    ("claim_submission_lag",           frozenset(["district"])             ): "T200",
    ("claim_submission_lag",           frozenset(["block"])                ): "T242",
    ("top_hospitals_by_payment",       frozenset()                         ): "D63",

    # ── Specialty / procedure / disease ──────────────────────────────────────
    ("procedure_financials",           frozenset()                         ): "D116",
    ("procedure_rejection_rates",      frozenset()                         ): "D117",
    ("procedure_rejection_rates",      frozenset(["district"])             ): "T197",
    ("specialty_performance",          frozenset()                         ): "D118",
    ("specialty_performance",          frozenset(["specialty"])            ): "T155",
    ("procedure_mix_pub_priv",         frozenset(["district"])             ): "T220",
    ("procedure_mix_pub_priv",         frozenset(["district", "district_2"])): "T283",
    ("maternal_case_rate",             frozenset()                         ): "D91",
    ("maternal_case_rate",             frozenset(["district"])             ): "T183",
    ("maternal_case_rate",             frozenset(["block"])                ): "T237",
    ("maternal_case_rate",             frozenset(["district", "district_2"])): "T267",
    ("communicable_case_rate",         frozenset()                         ): "D92",
    ("communicable_case_rate",         frozenset(["district"])             ): "T185",
    ("communicable_case_rate",         frozenset(["block"])                ): "T239",
    ("communicable_case_rate",         frozenset(["district", "district_2"])): "T269",
    ("ncd_case_rate",                  frozenset()                         ): "D121",
    ("ncd_case_rate",                  frozenset(["district"])             ): "T184",
    ("ncd_case_rate",                  frozenset(["block"])                ): "T238",
    ("ncd_case_rate",                  frozenset(["district", "district_2"])): "T268",
    ("injury_caseload",                frozenset()                         ): "D94",
    ("disease_mix_by_geography",       frozenset()                         ): "D90",
    ("disease_mix_by_geography",       frozenset(["district"])             ): "T93",
    ("disease_mix_by_geography",       frozenset(["block"])                ): "T109",
    ("diagnosis_procedure_combos",     frozenset()                         ): "D119",
    ("diagnosis_procedure_combos",     frozenset(["district"])             ): "T219",
    ("diagnosis_procedure_combos",     frozenset(["block"])                ): "T248",

    # ── Portability ──────────────────────────────────────────────────────────
    ("portability_volume",             frozenset(["district", "district_2"])): "T127",
    ("top_procedures",                 frozenset(["district", "district_2"])): "T125",
    ("top_diagnoses",                  frozenset(["district", "district_2"])): "T126",
    ("clinician_workload",             frozenset(["hospital"])             ): "T148",
    ("bed_overcrowding",               frozenset(["hospital"])             ): "T152",
    ("portability_detail",             frozenset()                         ): "D125",
    ("portability_detail",             frozenset(["district"])             ): "T187",
    ("portability_detail",             frozenset(["block"])                ): "T247",
    ("portability_detail",             frozenset(["district", "district_2"])): "T265",

    # ── Outcomes ─────────────────────────────────────────────────────────────
    ("readmission_rate",               frozenset()                         ): "D77",
    ("readmission_rate",               frozenset(["hospital"])             ): "T153",
    ("readmission_rate",               frozenset(["district"])             ): "T94",
    ("readmission_rate",               frozenset(["district", "district_2"])): "T277",
    ("mortality_rate",                 frozenset()                         ): "D86",
    ("mortality_rate",                 frozenset(["hospital"])             ): "T145",
    ("mortality_rate",                 frozenset(["district"])             ): "T89",
    ("mortality_rate",                 frozenset(["specialty"])            ): "T157",
    ("mortality_rate",                 frozenset(["block"])                ): "T107",
    ("mortality_rate",                 frozenset(["district", "district_2"])): "T281",
    ("lama_dama_rate",                 frozenset()                         ): "D87",
    ("lama_dama_rate",                 frozenset(["hospital"])             ): "T144",
    ("lama_dama_rate",                 frozenset(["district"])             ): "T88",
    ("lama_dama_rate",                 frozenset(["block"])                ): "T108",
    ("lama_dama_rate",                 frozenset(["district", "district_2"])): "T119",
    ("biometric_auth_discharge",       frozenset()                         ): "D88",
    ("biometric_auth_discharge",       frozenset(["district"])             ): "T97",
    ("biometric_auth_discharge",       frozenset(["block"])                ): "T240",
    ("biometric_auth_discharge",       frozenset(["district", "district_2"])): "T278",
    ("medicine_provision",             frozenset()                         ): "D89",
    ("medicine_provision",             frozenset(["district"])             ): "T98",
    ("medicine_provision",             frozenset(["block"])                ): "T241",
    ("medicine_provision",             frozenset(["district", "district_2"])): "T279",

    # ── Access & equity ──────────────────────────────────────────────────────
    ("gender_treatment_ratio",         frozenset()                         ): "D78",
    ("gender_treatment_ratio",         frozenset(["district"])             ): "T90",
    ("gender_treatment_ratio",         frozenset(["block"])                ): "T103",
    ("elderly_utilization",            frozenset()                         ): "D79",
    ("elderly_utilization",            frozenset(["district"])             ): "T91",
    ("zero_utilization_blocks",        frozenset()                         ): "D80",
    ("zero_utilization_blocks",        frozenset(["district"])             ): "T180",
    ("public_private_comparison",      frozenset()                         ): "D82",
    ("public_private_comparison",      frozenset(["district"])             ): "T207",
    ("public_private_comparison",      frozenset(["block"])                ): "T245",
    ("public_private_comparison",      frozenset(["district", "district_2"])): "T120",
    ("utilization_by_source",          frozenset()                         ): "D84",
    ("gender_procedure_disparity",     frozenset()                         ): "D85",
    ("out_of_district_treatment",      frozenset()                         ): "D107",
    ("out_of_district_treatment",      frozenset(["district"])             ): "T175",
    ("out_of_district_treatment",      frozenset(["block"])                ): "T234",
    ("out_of_district_treatment",      frozenset(["district", "district_2"])): "T262",
    ("patient_flow",                   frozenset()                         ): "D108",
    ("patient_flow",                   frozenset(["district"])             ): "T176",
    ("patient_flow",                   frozenset(["block"])                ): "T235",
    ("patient_flow",                   frozenset(["district", "district_2"])): "T263",
    ("case_rate_per_beneficiary",      frozenset()                         ): "D103",
    ("case_rate_per_beneficiary",      frozenset(["district"])             ): "T172",
    ("case_rate_per_beneficiary",      frozenset(["block"])                ): "T230",
    ("case_rate_per_beneficiary",      frozenset(["district", "district_2"])): "T259",
    ("bed_capacity_per_beneficiary",   frozenset()                         ): "D102",
    ("bed_capacity_per_beneficiary",   frozenset(["district"])             ): "T171",
    ("bed_capacity_per_beneficiary",   frozenset(["district", "district_2"])): "T258",
    ("underperforming_districts",      frozenset()                         ): "D139",
    ("underperforming_districts",      frozenset(["district"])             ): "T206",
    ("expenditure_concentration",      frozenset()                         ): "D98",
    ("expenditure_concentration",      frozenset(["district"])             ): "T178",
    ("expenditure_concentration",      frozenset(["block"])                ): "T243",
    ("expenditure_concentration",      frozenset(["district", "district_2"])): "T264",

    # ── Compliance ────────────────────────────────────────────────────────────
    ("diagnosis_package_mismatch",     frozenset()                         ): "D129",
    ("diagnosis_package_mismatch",     frozenset(["district"])             ): "T191",
    ("diagnosis_package_mismatch",     frozenset(["district", "district_2"])): "T275",
    ("reserved_procedure_violations",  frozenset()                         ): "D136",
    ("reserved_procedure_violations",  frozenset(["district"])             ): "T204",
    ("duplicate_enrolment_correlation",frozenset()                         ): "D137",
}

# ── Step 2: for each intent, which entity slots to attempt to extract ─────────
# Only list slots that are actually used by that intent's lookup entries.
# Entities not in this list will never be extracted for that intent.

INTENT_SLOTS: dict[str, list[str]] = {
    # ── Enrollment ────────────────────────────────────────────────────────────
    "enrollment_count":               ["district", "block", "division", "year", "district_2"],
    "enrollment_summary_by_district": [],
    "enrollment_summary_by_division": [],
    "enrollment_gender_breakdown":    ["district", "block"],
    "enrollment_age_distribution":    ["district", "block"],
    "enrollment_source_breakdown":    ["district", "block"],
    "enrollment_bis_status":          ["district", "block"],
    "enrollment_mobile_coverage":     ["district", "block"],
    # ── Hospital ──────────────────────────────────────────────────────────────
    "hospital_count":                 ["district", "block"],
    "hospital_count_by_district":     [],
    "hospital_density":               [],
    "specialty_coverage":             ["district", "block"],
    "hospital_license_status":        ["hospital", "district", "block"],
    "hospital_bed_capacity":          ["district", "block"],
    "hospital_staff_ratio":           ["district", "block"],
    "hospital_performance":           ["hospital"],
    "hospital_specialties":           ["hospital"],
    "hospital_type_utilization":      ["district", "block", "division"],
    # ── Claims ────────────────────────────────────────────────────────────────
    "claims_total":                   ["month", "year"],
    "case_volume_trend":              ["district", "block", "hospital", "division", "year"],
    "claims_summary_by_district":     [],
    "claims_summary_by_division":     [],
    "claims_summary":                 ["district", "block", "division", "division_2", "district_2"],
    "claim_status_distribution":      ["district", "block"],
    "claims_by_status":               ["claim_status", "district"],
    "claim_approval_rate":            ["hospital", "district", "district_2"],
    "case_volume_by_district":        ["year"],
    "block_case_volume":              ["district"],
    "annual_totals":                  ["year", "district"],
    "district_comparison":            ["district", "district_2"],
    # ── Specialty ─────────────────────────────────────────────────────────────
    "specialty_utilization":          ["specialty", "district", "block"],
    "specialty_by_district":          ["specialty"],
    "top_hospitals_by_specialty":     ["specialty"],
    "top_procedures":                 ["district", "block", "division", "year", "district_2"],
    "top_diagnoses":                  ["hospital", "block", "district", "division", "district_2"],
    "disease_category_breakdown":     ["district", "block"],
    "disease_category_trend":         ["diagnosis_category", "district", "division"],
    "seasonal_pattern":               ["diagnosis_category"],
    # ── Financial ─────────────────────────────────────────────────────────────
    "settlement_tat":                 ["district", "block", "specialty", "division", "month", "year", "district_2"],
    "settlement_tat_portability":     [],
    "settlement_tat_by_district":     [],
    "rejection_rate":                 ["district", "block", "month", "year", "division", "district_2"],
    "rejection_rate_trend":           [],
    "financial_summary":              ["district", "block", "year"],
    "top_hospitals_by_claims":        ["district", "block", "division"],
    # ── Portability ──────────────────────────────────────────────────────────
    "portability_volume":             ["district", "block", "district_2"],
    "portability_financials":         [],
    "portability_trend":              [],
    # ── Other existing ───────────────────────────────────────────────────────
    "discharge_distribution":         ["district", "block"],

    # ── Enrolment quality / funnel (NEW) ─────────────────────────────────────
    "beneficiary_utilization_gap":    ["district", "block"],
    "enrolment_to_card_lag":          ["district"],
    "enrolment_rejection_rate":       ["district", "block", "district_2"],
    "authentication_mode_breakdown":  ["district"],
    "profile_completeness":           ["district", "block", "district_2"],
    "duplicate_beneficiaries":        ["district", "block", "district_2"],
    "card_status_distribution":       ["district", "block", "district_2"],
    "enrolment_trend":                [],
    "beneficiary_hospital_ratio":     ["district", "block", "district_2"],
    "card_issuance_speed":            ["district", "block", "district_2"],
    "early_admission_rate":           ["district", "block", "district_2"],
    "enrolment_to_treatment_funnel":  ["district", "block"],

    # ── Hospital compliance / quality (NEW) ──────────────────────────────────
    "unauthorized_specialty_billing": ["district"],
    "bed_overcrowding":               ["district", "hospital"],
    "accreditation_status":           ["district"],
    "infrastructure_gaps":            [],
    "delisted_with_cases":            ["district"],
    "average_length_of_stay":         ["hospital", "specialty", "district", "district_2"],
    "clinician_workload":             ["district", "hospital"],
    "hospital_concentration":         ["district"],
    "blocks_without_hospitals":       ["district"],

    # ── Claims / financial analytics (NEW) ───────────────────────────────────
    "claim_haircut":                  ["district", "district_2"],
    "claim_value_by_procedure":       ["district", "hospital", "specialty", "block", "district_2"],
    "pending_claims_aging":           ["district"],
    "failed_payments":                ["district", "hospital", "district_2"],
    "documents_per_claim":            ["district", "district_2"],
    "adjudication_query_rate":        [],
    "rejection_reasons":              [],
    "expenditure_trend":              [],
    "per_beneficiary_spend":          ["district", "division", "district_2"],
    "preauth_analysis":               ["district", "hospital", "block", "month", "year", "district_2"],
    "addon_procedures":               ["hospital"],
    "claim_submission_lag":           ["district", "block"],
    "top_hospitals_by_payment":       [],

    # ── Specialty / procedure / disease (NEW) ────────────────────────────────
    "procedure_financials":           [],
    "procedure_rejection_rates":      ["district"],
    "specialty_performance":          ["specialty"],
    "procedure_mix_pub_priv":         ["district", "district_2"],
    "maternal_case_rate":             ["district", "block", "district_2"],
    "communicable_case_rate":         ["district", "block", "district_2"],
    "ncd_case_rate":                  ["district", "block", "district_2"],
    "injury_caseload":                [],
    "disease_mix_by_geography":       ["district", "block"],
    "diagnosis_procedure_combos":     ["district", "block"],

    # ── Portability (NEW) ────────────────────────────────────────────────────
    "portability_detail":             ["district", "block", "district_2"],

    # ── Outcomes (NEW) ───────────────────────────────────────────────────────
    "readmission_rate":               ["hospital", "district", "district_2"],
    "mortality_rate":                 ["hospital", "district", "specialty", "block", "district_2"],
    "lama_dama_rate":                 ["hospital", "district", "block", "district_2"],
    "biometric_auth_discharge":       ["district", "block", "district_2"],
    "medicine_provision":             ["district", "block", "district_2"],

    # ── Access & equity (NEW) ────────────────────────────────────────────────
    "gender_treatment_ratio":         ["district", "block"],
    "elderly_utilization":            ["district"],
    "zero_utilization_blocks":        ["district"],
    "public_private_comparison":      ["district", "block", "district_2"],
    "utilization_by_source":          [],
    "gender_procedure_disparity":     [],
    "out_of_district_treatment":      ["district", "block", "district_2"],
    "patient_flow":                   ["district", "block", "district_2"],
    "case_rate_per_beneficiary":      ["district", "block", "district_2"],
    "bed_capacity_per_beneficiary":   ["district", "district_2"],
    "underperforming_districts":      ["district"],
    "expenditure_concentration":      ["district", "block", "district_2"],

    # ── Compliance (NEW) ─────────────────────────────────────────────────────
    "diagnosis_package_mismatch":     ["district", "district_2"],
    "reserved_procedure_violations":  ["district"],
    "duplicate_enrolment_correlation":[],
}

INTENT_LIST = sorted(INTENT_SLOTS.keys()) + ["no_match"]

# ── Domain groupings for hierarchical 2-step classification ──────────────────
# Each domain maps to the list of intent names the LLM may return in Step 2.
# New intents must be added here AND to INTENT_SLOTS and INTENT_LOOKUP.

INTENT_LIST_BY_DOMAIN: dict[str, list[str]] = {
    "ENROLMENT": [
        "enrollment_count",
        "enrollment_summary_by_district",
        "enrollment_summary_by_division",
        "enrollment_gender_breakdown",
        "enrollment_age_distribution",
        "enrollment_source_breakdown",
        "enrollment_bis_status",
        "enrollment_mobile_coverage",
        "beneficiary_utilization_gap",
        "enrolment_to_card_lag",
        "enrolment_rejection_rate",
        "authentication_mode_breakdown",
        "profile_completeness",
        "duplicate_beneficiaries",
        "card_status_distribution",
        "enrolment_trend",
        "beneficiary_hospital_ratio",
        "card_issuance_speed",
        "early_admission_rate",
        "enrolment_to_treatment_funnel",
    ],
    "HOSPITAL": [
        "hospital_count",
        "hospital_count_by_district",
        "hospital_density",
        "specialty_coverage",
        "hospital_license_status",
        "hospital_bed_capacity",
        "hospital_staff_ratio",
        "hospital_performance",
        "hospital_specialties",
        "hospital_type_utilization",
        "unauthorized_specialty_billing",
        "bed_overcrowding",
        "accreditation_status",
        "infrastructure_gaps",
        "delisted_with_cases",
        "average_length_of_stay",
        "clinician_workload",
        "hospital_concentration",
        "blocks_without_hospitals",
    ],
    "CLAIMS": [
        "claims_total",
        "claims_summary",
        "claims_summary_by_district",
        "claims_summary_by_division",
        "claim_status_distribution",
        "claims_by_status",
        "claim_approval_rate",
        "case_volume_trend",
        "case_volume_by_district",
        "block_case_volume",
        "annual_totals",
        "district_comparison",
        "settlement_tat",
        "settlement_tat_portability",
        "settlement_tat_by_district",
        "rejection_rate",
        "rejection_rate_trend",
        "financial_summary",
        "top_hospitals_by_claims",
        "top_hospitals_by_payment",
        "claim_haircut",
        "claim_value_by_procedure",
        "pending_claims_aging",
        "failed_payments",
        "documents_per_claim",
        "adjudication_query_rate",
        "rejection_reasons",
        "expenditure_trend",
        "per_beneficiary_spend",
        "preauth_analysis",
        "addon_procedures",
        "claim_submission_lag",
    ],
    "SPECIALTY": [
        "specialty_utilization",
        "specialty_by_district",
        "top_hospitals_by_specialty",
        "top_procedures",
        "top_diagnoses",
        "disease_category_breakdown",
        "disease_category_trend",
        "seasonal_pattern",
        "procedure_financials",
        "procedure_rejection_rates",
        "specialty_performance",
        "procedure_mix_pub_priv",
        "maternal_case_rate",
        "communicable_case_rate",
        "ncd_case_rate",
        "injury_caseload",
        "disease_mix_by_geography",
        "diagnosis_procedure_combos",
    ],
    "PORTABILITY": [
        "portability_volume",
        "portability_financials",
        "portability_trend",
        "discharge_distribution",
        "portability_detail",
    ],
    "OUTCOMES": [
        "readmission_rate",
        "mortality_rate",
        "lama_dama_rate",
        "biometric_auth_discharge",
        "medicine_provision",
    ],
    "ACCESS_EQUITY": [
        "gender_treatment_ratio",
        "elderly_utilization",
        "zero_utilization_blocks",
        "public_private_comparison",
        "utilization_by_source",
        "gender_procedure_disparity",
        "out_of_district_treatment",
        "patient_flow",
        "case_rate_per_beneficiary",
        "bed_capacity_per_beneficiary",
        "underperforming_districts",
        "expenditure_concentration",
    ],
    "COMPLIANCE": [
        "diagnosis_package_mismatch",
        "reserved_procedure_violations",
        "duplicate_enrolment_correlation",
    ],
}

# ── Collision detection — fail fast at import time ────────────────────────────
def _validate_lookup() -> None:
    seen: dict[tuple, str] = {}
    for key, qid in INTENT_LOOKUP.items():
        if key in seen and seen[key] != qid:
            raise ValueError(
                f"INTENT_LOOKUP collision: {key!r} maps to both '{seen[key]}' and '{qid}'"
            )
        seen[key] = qid

_validate_lookup()
