import { useState, useMemo } from "react";
import { ChevronDown, ChevronRight } from "lucide-react";

// Per-gamma reports (generated by phase5c_gamma_reports.py)
import gamma01Raw from "@/data/metainsights/gamma_0.1_report.md?raw";
import gamma03Raw from "@/data/metainsights/gamma_0.3_report.md?raw";
import gamma05Raw from "@/data/metainsights/gamma_0.5_report.md?raw";
import gamma07Raw from "@/data/metainsights/gamma_0.7_report.md?raw";
import gamma09Raw from "@/data/metainsights/gamma_0.9_report.md?raw";

const GAMMA_REPORTS: Record<number, string> = {
  0.1: gamma01Raw,
  0.3: gamma03Raw,
  0.5: gamma05Raw,
  0.7: gamma07Raw,
  0.9: gamma09Raw,
};

// --- Types ---

interface Insight {
  leadline: string;
  bullets: string[];
  category: Category;
}

type Category = "all" | "claims" | "hospital" | "beneficiary";

const CATEGORIES: { key: Category; label: string }[] = [
  { key: "all", label: "All" },
  { key: "claims", label: "Claims & Treatment" },
  { key: "hospital", label: "Hospital Infrastructure & Speciality" },
  { key: "beneficiary", label: "Beneficiary Enrolment & Uptake" },
];

const GAMMA_LEVELS = [0.1, 0.3, 0.5, 0.7, 0.9] as const;

// Map section headings to categories
const SECTION_CATEGORY: Record<string, Category> = {
  "Claims Processing & Treatment Patterns": "claims",
  "District-Level Monthly Performance Trends": "beneficiary",
  "Hospital Infrastructure & Specialty Capacity": "hospital",
  "Beneficiary Enrolment & Scheme Uptake": "beneficiary",
};

// --- Parser ---

/** Parse a report that uses bold leadlines (**...**) + numbered bullets */
function parseReport(md: string): Insight[] {
  const insights: Insight[] = [];
  let currentCategory: Category = "claims";

  const lines = md.split("\n");
  let i = 0;

  while (i < lines.length) {
    const line = lines[i];

    // Section header (## level)
    if (line.startsWith("## ") && !line.startsWith("### ")) {
      const heading = line.replace(/^## /, "").trim();
      if (SECTION_CATEGORY[heading]) {
        currentCategory = SECTION_CATEGORY[heading];
      }
      i++;
      continue;
    }

    // Bold leadline: **...**
    if (line.startsWith("**") && line.trimEnd().endsWith("**")) {
      const leadline = line.trim().replace(/^\*\*/, "").replace(/\*\*\s*$/, "").trim();
      const bullets: string[] = [];
      i++;

      // Collect numbered bullets
      while (i < lines.length) {
        const bLine = lines[i].trim();
        if (/^\d+\.\s/.test(bLine)) {
          bullets.push(bLine.replace(/^\d+\.\s*/, ""));
          i++;
        } else if (bLine === "") {
          i++;
          if (i < lines.length && /^\d+\.\s/.test(lines[i].trim())) {
            continue;
          }
          break;
        } else {
          break;
        }
      }

      if (leadline) {
        insights.push({ leadline, bullets, category: currentCategory });
      }
      continue;
    }

    // Also handle ### heading + paragraph + dash-bullet format (overview style)
    if (line.startsWith("### ")) {
      const heading = line.replace(/^### /, "").trim();
      i++;

      const bullets: string[] = [];
      let paragraph = "";

      while (i < lines.length) {
        const bLine = lines[i].trim();
        if (bLine.startsWith("## ") || bLine.startsWith("### ") || bLine.startsWith("---")) {
          break;
        }
        if (bLine.startsWith("- ")) {
          bullets.push(bLine.replace(/^- /, ""));
          i++;
        } else if (/^\d+\.\s/.test(bLine)) {
          bullets.push(bLine.replace(/^\d+\.\s*/, ""));
          i++;
        } else if (bLine !== "" && !paragraph) {
          paragraph = bLine;
          i++;
        } else {
          i++;
        }
      }

      const allBullets: string[] = [];
      if (paragraph) allBullets.push(paragraph);
      allBullets.push(...bullets);

      if (heading) {
        insights.push({ leadline: heading, bullets: allBullets, category: currentCategory });
      }
      continue;
    }

    i++;
  }

  return insights;
}

// --- Component ---

function InsightCard({ insight }: { insight: Insight }) {
  const [expanded, setExpanded] = useState(false);

  return (
    <button
      onClick={() => setExpanded(!expanded)}
      className="w-full text-left rounded-lg border border-border bg-card p-4 hover:shadow-sm transition-shadow"
    >
      <div className="flex items-start gap-2">
        <div className="shrink-0 mt-0.5 text-muted-foreground">
          {expanded ? (
            <ChevronDown className="h-4 w-4" />
          ) : (
            <ChevronRight className="h-4 w-4" />
          )}
        </div>
        <p className="text-sm text-foreground leading-relaxed">
          {insight.leadline}
        </p>
      </div>

      {expanded && insight.bullets.length > 0 && (
        <ol className="mt-3 ml-6 space-y-1.5 list-decimal list-outside text-sm text-muted-foreground leading-relaxed">
          {insight.bullets.map((b, j) => (
            <li key={j} className="pl-1">
              {b}
            </li>
          ))}
        </ol>
      )}
    </button>
  );
}

export function AnomaliesView() {
  const [gamma, setGamma] = useState<number>(0.5);
  const [category, setCategory] = useState<Category>("all");

  const insights = useMemo(() => {
    const raw = GAMMA_REPORTS[gamma] || GAMMA_REPORTS[0.5];
    const parsed = parseReport(raw);
    if (category === "all") return parsed;
    return parsed.filter((ins) => ins.category === category);
  }, [gamma, category]);

  return (
    <div className="flex flex-1 flex-col min-h-0">
      {/* Controls bar — two rows */}
      <div className="shrink-0 border-b border-border bg-[hsl(var(--sidebar-bg))]">
        {/* Row 1: Gamma toggle */}
        <div className="flex items-center justify-center gap-4 px-6 py-2.5 border-b border-border/50">
          <span className="text-xs font-medium text-muted-foreground shrink-0">
            Anomaly type
          </span>
          <div className="flex items-center gap-2">
            <span className="text-[11px] text-muted-foreground">General</span>
            <div className="flex items-center gap-0">
              <div className="relative flex items-center">
                <div className="absolute h-0.5 bg-border rounded-full" style={{ width: `${(GAMMA_LEVELS.length - 1) * 24}px`, left: 6, top: '50%', transform: 'translateY(-50%)' }} />
                <div className="flex items-center gap-3 relative">
                  {GAMMA_LEVELS.map((g) => (
                    <button
                      key={g}
                      onClick={() => setGamma(g)}
                      className={`w-3 h-3 rounded-full border-2 transition-colors ${
                        gamma === g
                          ? "bg-[#0f4c5c] border-[#0f4c5c]"
                          : "bg-background border-border hover:border-[#0f4c5c]/50"
                      }`}
                      aria-label={`Gamma ${g}`}
                    />
                  ))}
                </div>
              </div>
            </div>
            <span className="text-[11px] text-muted-foreground">Specific</span>
          </div>
        </div>

        {/* Row 2: Category filter */}
        <div className="flex items-center justify-center gap-1.5 px-6 py-2">
          {CATEGORIES.map((c) => (
            <button
              key={c.key}
              onClick={() => setCategory(c.key)}
              className={`px-3 py-1 text-xs font-medium rounded-md transition-colors ${
                category === c.key
                  ? "bg-[#0f4c5c] text-white"
                  : "bg-muted text-muted-foreground hover:bg-background"
              }`}
            >
              {c.label}
            </button>
          ))}
        </div>
      </div>

      {/* Insights list */}
      <div className="flex-1 overflow-y-auto scrollbar-thin px-6 py-4">
        <div className="max-w-4xl mx-auto space-y-3">
          <p className="text-xs text-muted-foreground mb-2">
            {insights.length} insight{insights.length !== 1 ? "s" : ""}
          </p>
          {insights.map((ins, i) => (
            <InsightCard key={`${gamma}-${category}-${i}`} insight={ins} />
          ))}
        </div>
      </div>
    </div>
  );
}
